version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          # --group needs pip 25.1 or newer.
          command: python -m pip install --upgrade pip && pip install --group runtime --group test && pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
